### ISSUE TITLE
Where can the user get the adversarial example when ab-crown return unsafe result?

### ISSUE THREAD

**Issue by CRhapsody** [Verified-Intelligence/alpha-beta-CROWN#25]
When I test a robustness property using this tool, the result of program return 'unsafe', but I can not find the corresponding adversarial example.

**Comment by huanzhang12** [comment]
Counterexamples can be saved via setting "general"->"save_adv_example" to true. 

https://github.com/Verified-Intelligence/alpha-beta-CROWN/blob/7b3d507caf40a5f42d99f6894373526c6fd615b7/complete_verifier/docs/abcrown_all_params.yaml#L9

(the above file is a documentation showing where you should change in your own config file. Do not change `abcrown_all_params.yaml` directly)

However, there are some cases the counterexamples were not saved due to an implementation glitch. In these cases, you can set a breakpoint when counterexample is found and dump it manually. We will fix it in the next release.

**Comment by kamdoumloich** [comment]
I tested it, but the output file (out.txt) that I received is a binary file. How can I read its content?

**Comment by shizhouxing** [comment]
Hi @kamdoumloich , the counterexample is saved to a file according to `--cex_path` you specify. By default, it's `./test_cex.txt`:

https://github.com/Verified-Intelligence/alpha-beta-CROWN/blob/main/complete_verifier/arguments.py#L740
